---
apiVersion: v1
kind: Service
metadata:
  name: send-notification
  labels:
    app: office-space
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: office-space
    tier: notification
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-notification
  labels:
    app: office-space
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: office-space
      tier: notification
  template:
    metadata:
      labels:
        app: office-space
        tier: notification
    spec:
      containers:
        - image: tgi01054/spring-demo-ibm-send-notification 
          imagePullPolicy: Always
          name: send-notification
          env:
            - name: GMAIL_SENDER_USER
              value: 'tgi01054@gmail.com'
            - name: GMAIL_SENDER_PASSWORD
              value: '8234kknd^&'
            - name: EMAIL_RECEIVER
              value: 'tgi01054@gmail.com'
            - name: OPENWHISK_API_URL_SLACK
              value: ''
            - name: NOTIFICATION_MESSAGE
              value: 'Your balance is over $50,000.00'
            - name: OPENWHISK_API_URL_EMAIL
              value: ''
          ports:
            - containerPort: 8080
